### ISSUE TITLE
Sessions out of sync

### ISSUE THREAD

**Issue by Mikunj** [loki-project/loki-messenger-ios#24]
**Describe the bug**
Sometimes after communicating for a while the sessions start to become out of sync, prompting the mobile user to reset session.

This unfortunately happens on every message received.

**To reproduce**
No clue, will need to investigate

**Comment by gmbnt** [comment]
@Mikunj didn't you fix this the other day?

**Comment by Mikunj** [comment]
I never got it to reproduce so we can close this for now and open it back up if we run into it again
