### ISSUE TITLE
Restoring via seed generates a different public key.

### ISSUE THREAD

**Issue by GraftNugget** [loki-project/loki-messenger-ios#30]
**Describe the bug**
In the current TestFlight IOS LokiNugget messenger- If you restore from a seed generated from a seperate device (in my case OSX), a different public key is generated.

**To reproduce**
Generate a key pair in Loki messenger (OSX) and restore via seed into IOS. The key generated from seed in IOS will be completely different.

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: 12.3.1
 - Version of Loki Messenger or latest commit hash: TestFlight

**Comment by necro-nemesis** [comment]
Had the same thing occur.

**Comment by gmbnt** [comment]
This has been fixed
